version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "activity-log-topic:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "false"
    networks:
      - app-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  task-management-activities-logging:
    build:
      context: ./TaskManagementActivitiesLogging
      dockerfile: Dockerfile
    ports:
      - "5176:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - KafkaConfigurationOptions__BootstrapServers=kafka:9093
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=activities_logging;Username=postgres;Password=3216733
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  task-management-service:
    build:
      context: ./TaskManagementService
      dockerfile: Dockerfile
    ports:
      - "5175:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - KafkaConfigurationOptions__BootstrapServers=kafka:9093
      - ITaskManagementActivitiesLoggingHttpClient=http://task-management-activities-logging:80
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=activities_logging;Username=postgres;Password=3216733
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3216733
      POSTGRES_DB: activities_logging
    ports:
    - "5432:5432"
    networks:
    - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d activities_logging"]
      interval: 5s
      timeout: 5s
      retries: 10